require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "/**/schema.rb"

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - "/**/migrate/*"


Metrics:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
