name: Rails app CI
run-name: Running rspecs & rubocop
on: 
  pull_request:
    types:
      - opened
  push:

jobs:
  rspec-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: polloloco_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/polloloco_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby & gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup db
        run: bin/rails db:schema:load

      - name: Run rspec
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby & gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop
